# docker-compose.yaml

services:
  apigen:
    build: .
    container_name: apigen_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      # Map poort 8001 op de host naar poort 8000 in de container.
      - "127.0.0.1:8001:8000"
    volumes:
      # Mount de volledige projectmap ('.') naar de /app map in de container.
      # 1. Dit maakt lokale bestanden (zoals alembic.ini) direct beschikbaar.
      # 2. Wijzigingen in je code zijn direct zichtbaar in de container (handig voor dev).
      # 3. Het SQLite databasebestand wordt nu in je projectmap op je computer opgeslagen.
      - .:/app

# De aparte 'volumes:' sleutel onderaan is niet meer nodig met deze aanpak.